### ISSUE TITLE
All features passed displayed before feature results are shown when using tags

### ISSUE THREAD

**Issue by leiyangyou** [meadsteve/white-bread#27] opened 2015-11-19 06:04 UTC

**Comment by meadsteve** [comment] 2015-11-19 08:35
@leiyangyou sorry I'm not sure I understand what the issue is. Could you give an example or try rewording the issue?

**Comment by leiyangyou** [comment] 2015-11-19 08:40
Hi @meadsteve,

here is an example output, initially I thought it was to do with the usage
of tags. looks like that's not the case

mix white_bread.run

```
Navigate to New Post ---> ok
Shows home feed ---> ok
All features passed.
Upvote a post ---> ok
Cancel a post upvote ---> ok
Upvote a downvoted post ---> ok
Downvote a post ---> ok
Cancel a post downvote ---> ok
Downvote a upvoted post ---> ok
```

**Comment by meadsteve** [comment] 2015-11-19 08:43
@leiyangyou that makes sense. Thanks for clarifying. I think it's because the progress reporter listens to messages and outputs asynchronously yet the feature result is directly output by the main process meaning it can happen before the progress reporter has printed all the other results.

I'll take a look at reworking this as it doesn't make any sense for ```All features passed``` to be printed in the middle.

**Comment by meadsteve** [comment] 2015-11-19 09:31
@leiyangyou this should be fixed by 2e4fe9b87eba089210f222ee95d91cf66e1a6870

**Comment by leiyangyou** [comment] 2015-11-19 11:57
Thanks @meadsteve

**Closed** 2015-11-20 09:49 UTC
